const wt = {
  location: {
    name: "Connaught Place",
    region: "Delhi",
    country: "India",
    lat: 28.633,
    lon: 77.217,
    tz_id: "Asia/Kolkata",
    localtime_epoch: 1789648963,
    localtime: "2026-09-17 18:12",
  },
  current: {
    last_updated_epoch: 1789648200,
    last_updated: "2026-09-17 18:00",
    temp_c: 33.2,
    temp_f: 91.8,
    is_day: 1,
    condition: {
      text: "Clear",
      icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
      code: 1000,
    },
    wind_mph: 8.3,
    wind_kph: 13.3,
    wind_degree: 15,
    wind_dir: "NNE",
    pressure_mb: 1004,
    pressure_in: 29.64,
    precip_mm: 0,
    precip_in: 0,
    humidity: 44,
    cloud: 19,
    feelslike_c: 35,
    feelslike_f: 95,
    windchill_c: 33.2,
    windchill_f: 91.8,
    heatindex_c: 35.7,
    heatindex_f: 96.2,
    dewpoint_c: 19.2,
    dewpoint_f: 66.6,
    vis_km: 10,
    vis_miles: 6,
    uv: 0,
    gust_mph: 9,
    gust_kph: 14.5,
    will_it_rain: 0,
    chance_of_rain: 2,
    will_it_snow: 0,
    chance_of_snow: 0,
    wetbulb_c: 23.4,
    wetbulb_f: 74.1,
    air_quality: {
      co: 1113,
      no2: 42.8,
      o3: 148,
      so2: 43.4,
      pm2_5: 59.3,
      pm10: 62.6,
      "us-epa-index": 3,
      "gb-defra-index": 8,
    },
  },
  forecast: {
    forecastday: [
      {
        date: "2026-09-17",
        date_epoch: 1789603200,
        day: {
          maxtemp_c: 35.8,
          maxtemp_f: 96.4,
          mintemp_c: 25.8,
          mintemp_f: 78.4,
          avgtemp_c: 30.6,
          avgtemp_f: 87.1,
          maxwind_mph: 16.3,
          maxwind_kph: 26.3,
          totalprecip_mm: 1.23,
          totalprecip_in: 0.05,
          totalsnow_cm: 0,
          avgvis_km: 9.1,
          avgvis_miles: 5,
          avghumidity: 53,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 57,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Smoky haze",
            icon: "//cdn.weatherapi.com/weather/64x64/day/149.png",
            code: 1036,
          },
          uv: 6.9,
          avgwetbulb_c: 22.9,
          avgwetbulb_f: 73.2,
          maxwetbulb_c: 23.9,
          maxwetbulb_f: 75,
        },
        astro: {
          sunrise: "06:07 AM",
          sunset: "06:24 PM",
          moonrise: "12:16 PM",
          moonset: "10:25 PM",
          moon_phase: "First Quarter",
          moon_illumination: 42,
          is_moon_up: 1,
          is_sun_up: 1,
        },
        hour: [
          {
            time_epoch: 1789583400,
            time: "2026-09-17 00:00",
            temp_c: 29.2,
            temp_f: 84.5,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 181,
            wind_dir: "S",
            pressure_mb: 1005,
            pressure_in: 29.69,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 61,
            cloud: 5,
            feelslike_c: 31.4,
            feelslike_f: 88.5,
            windchill_c: 29.2,
            windchill_f: 84.5,
            heatindex_c: 31.7,
            heatindex_f: 89.1,
            dewpoint_c: 20.8,
            dewpoint_f: 69.4,
            will_it_rain: 0,
            chance_of_rain: 4,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.3,
            gust_kph: 19.8,
            uv: 0,
            wetbulb_c: 23.2,
            wetbulb_f: 73.8,
          },
          {
            time_epoch: 1789587000,
            time: "2026-09-17 01:00",
            temp_c: 29.2,
            temp_f: 84.6,
            is_day: 0,
            condition: {
              text: "Partly Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 218,
            wind_dir: "SW",
            pressure_mb: 1005,
            pressure_in: 29.69,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 59,
            cloud: 27,
            feelslike_c: 31.2,
            feelslike_f: 88.2,
            windchill_c: 29.2,
            windchill_f: 84.6,
            heatindex_c: 31.5,
            heatindex_f: 88.7,
            dewpoint_c: 20.4,
            dewpoint_f: 68.7,
            will_it_rain: 0,
            chance_of_rain: 5,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 6.8,
            vis_miles: 4,
            gust_mph: 17,
            gust_kph: 27.4,
            uv: 0,
            wetbulb_c: 23,
            wetbulb_f: 73.4,
          },

          {
            time_epoch: 1789590600,
            time: "2026-09-17 02:00",
            temp_c: 29,
            temp_f: 84.2,
            is_day: 0,
            condition: {
              text: "Smoky haze",
              icon: "//cdn.weatherapi.com/weather/64x64/night/149.png",
              code: 1036,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 233,
            wind_dir: "SW",
            pressure_mb: 1005,
            pressure_in: 29.68,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 61,
            cloud: 3,
            feelslike_c: 31.2,
            feelslike_f: 88.2,
            windchill_c: 29,
            windchill_f: 84.3,
            heatindex_c: 31.4,
            heatindex_f: 88.6,
            dewpoint_c: 20.6,
            dewpoint_f: 69.2,
            will_it_rain: 0,
            chance_of_rain: 3,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 6.7,
            vis_miles: 4,
            gust_mph: 20.4,
            gust_kph: 32.8,
            uv: 0,
            wetbulb_c: 23.1,
            wetbulb_f: 73.6,
          },
          {
            time_epoch: 1789594200,
            time: "2026-09-17 03:00",
            temp_c: 28.9,
            temp_f: 84.1,
            is_day: 0,
            condition: {
              text: "Smoky haze",
              icon: "//cdn.weatherapi.com/weather/64x64/night/149.png",
              code: 1036,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 247,
            wind_dir: "WSW",
            pressure_mb: 1005,
            pressure_in: 29.67,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 61,
            cloud: 0,
            feelslike_c: 31,
            feelslike_f: 87.8,
            windchill_c: 28.9,
            windchill_f: 84.1,
            heatindex_c: 31.3,
            heatindex_f: 88.3,
            dewpoint_c: 20.6,
            dewpoint_f: 69,
            will_it_rain: 0,
            chance_of_rain: 3,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 6.6,
            vis_miles: 4,
            gust_mph: 20.7,
            gust_kph: 33.3,
            uv: 0,
            wetbulb_c: 23,
            wetbulb_f: 73.4,
          },
          {
            time_epoch: 1789597800,
            time: "2026-09-17 04:00",
            temp_c: 28.8,
            temp_f: 83.9,
            is_day: 0,
            condition: {
              text: "Smoky haze",
              icon: "//cdn.weatherapi.com/weather/64x64/night/149.png",
              code: 1036,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 269,
            wind_dir: "W",
            pressure_mb: 1005,
            pressure_in: 29.69,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 57,
            cloud: 94,
            feelslike_c: 30.3,
            feelslike_f: 86.5,
            windchill_c: 28.8,
            windchill_f: 83.9,
            heatindex_c: 30.6,
            heatindex_f: 87.1,
            dewpoint_c: 19.4,
            dewpoint_f: 67,
            will_it_rain: 0,
            chance_of_rain: 12,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 6.6,
            vis_miles: 4,
            gust_mph: 19.3,
            gust_kph: 31,
            uv: 0,
            wetbulb_c: 22.3,
            wetbulb_f: 72.1,
          },
          {
            time_epoch: 1789601400,
            time: "2026-09-17 05:00",
            temp_c: 27.6,
            temp_f: 81.6,
            is_day: 0,
            condition: {
              text: "Smoky haze",
              icon: "//cdn.weatherapi.com/weather/64x64/night/149.png",
              code: 1036,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 301,
            wind_dir: "WNW",
            pressure_mb: 1006,
            pressure_in: 29.7,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 62,
            cloud: 6,
            feelslike_c: 29.1,
            feelslike_f: 84.4,
            windchill_c: 27.6,
            windchill_f: 81.6,
            heatindex_c: 29.4,
            heatindex_f: 84.8,
            dewpoint_c: 19.8,
            dewpoint_f: 67.6,
            will_it_rain: 0,
            chance_of_rain: 4,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 6.6,
            vis_miles: 4,
            gust_mph: 18.4,
            gust_kph: 29.6,
            uv: 0,
            wetbulb_c: 22.1,
            wetbulb_f: 71.9,
          },
          {
            time_epoch: 1789605000,
            time: "2026-09-17 06:00",
            temp_c: 27.5,
            temp_f: 81.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 309,
            wind_dir: "NW",
            pressure_mb: 1006,
            pressure_in: 29.71,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 62,
            cloud: 5,
            feelslike_c: 28.9,
            feelslike_f: 84,
            windchill_c: 27.5,
            windchill_f: 81.4,
            heatindex_c: 29.2,
            heatindex_f: 84.5,
            dewpoint_c: 19.6,
            dewpoint_f: 67.3,
            will_it_rain: 0,
            chance_of_rain: 4,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 6.6,
            vis_miles: 4,
            gust_mph: 9,
            gust_kph: 14.5,
            uv: 0,
            wetbulb_c: 22,
            wetbulb_f: 71.6,
          },
          {
            time_epoch: 1789608600,
            time: "2026-09-17 07:00",
            temp_c: 28.2,
            temp_f: 82.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 308,
            wind_dir: "NW",
            pressure_mb: 1007,
            pressure_in: 29.73,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 58,
            cloud: 10,
            feelslike_c: 29.6,
            feelslike_f: 85.3,
            windchill_c: 28.2,
            windchill_f: 82.8,
            heatindex_c: 29.9,
            heatindex_f: 85.8,
            dewpoint_c: 19.3,
            dewpoint_f: 66.8,
            will_it_rain: 0,
            chance_of_rain: 3,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 6.8,
            vis_miles: 4,
            gust_mph: 5.6,
            gust_kph: 9,
            uv: 0.4,
            wetbulb_c: 22,
            wetbulb_f: 71.7,
          },
          {
            time_epoch: 1789612200,
            time: "2026-09-17 08:00",
            temp_c: 29.5,
            temp_f: 85.1,
            is_day: 1,
            condition: {
              text: "Partly Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 323,
            wind_dir: "NW",
            pressure_mb: 1007,
            pressure_in: 29.74,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 53,
            cloud: 53,
            feelslike_c: 30.9,
            feelslike_f: 87.6,
            windchill_c: 29.5,
            windchill_f: 85.1,
            heatindex_c: 31.2,
            heatindex_f: 88.2,
            dewpoint_c: 19.1,
            dewpoint_f: 66.3,
            will_it_rain: 0,
            chance_of_rain: 6,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 8.3,
            vis_miles: 5,
            gust_mph: 2.5,
            gust_kph: 4,
            uv: 1.5,
            wetbulb_c: 22.3,
            wetbulb_f: 72.1,
          },
          {
            time_epoch: 1789615800,
            time: "2026-09-17 09:00",
            temp_c: 30.3,
            temp_f: 86.6,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 1.6,
            wind_kph: 2.5,
            wind_degree: 242,
            wind_dir: "WSW",
            pressure_mb: 1008,
            pressure_in: 29.75,
            precip_mm: 0.07,
            precip_in: 0,
            snow_cm: 0,
            humidity: 52,
            cloud: 95,
            feelslike_c: 31.9,
            feelslike_f: 89.4,
            windchill_c: 30.3,
            windchill_f: 86.6,
            heatindex_c: 32.4,
            heatindex_f: 90.2,
            dewpoint_c: 19.5,
            dewpoint_f: 67.1,
            will_it_rain: 0,
            chance_of_rain: 17,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.3,
            gust_kph: 3.7,
            uv: 3.2,
            wetbulb_c: 22.8,
            wetbulb_f: 73,
          },
          {
            time_epoch: 1789619400,
            time: "2026-09-17 10:00",
            temp_c: 29.8,
            temp_f: 85.6,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 290,
            wind_dir: "WNW",
            pressure_mb: 1008,
            pressure_in: 29.76,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 56,
            cloud: 89,
            feelslike_c: 31.7,
            feelslike_f: 89.1,
            windchill_c: 29.8,
            windchill_f: 85.6,
            heatindex_c: 32,
            heatindex_f: 89.6,
            dewpoint_c: 20,
            dewpoint_f: 67.9,
            will_it_rain: 0,
            chance_of_rain: 11,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.2,
            gust_kph: 8.3,
            uv: 5.3,
            wetbulb_c: 22.9,
            wetbulb_f: 73.2,
          },
          {
            time_epoch: 1789623000,
            time: "2026-09-17 11:00",
            temp_c: 31.4,
            temp_f: 88.5,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 301,
            wind_dir: "WNW",
            pressure_mb: 1007,
            pressure_in: 29.74,
            precip_mm: 0.13,
            precip_in: 0.01,
            snow_cm: 0,
            humidity: 51,
            cloud: 77,
            feelslike_c: 33.5,
            feelslike_f: 92.3,
            windchill_c: 31.4,
            windchill_f: 88.5,
            heatindex_c: 34,
            heatindex_f: 93.2,
            dewpoint_c: 20,
            dewpoint_f: 68.1,
            will_it_rain: 0,
            chance_of_rain: 17,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4,
            gust_kph: 6.5,
            uv: 6.9,
            wetbulb_c: 23.4,
            wetbulb_f: 74.1,
          },
          {
            time_epoch: 1789626600,
            time: "2026-09-17 12:00",
            temp_c: 33.7,
            temp_f: 92.7,
            is_day: 1,
            condition: {
              text: "Partly Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 276,
            wind_dir: "W",
            pressure_mb: 1006,
            pressure_in: 29.71,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 44,
            cloud: 42,
            feelslike_c: 36,
            feelslike_f: 96.8,
            windchill_c: 33.8,
            windchill_f: 92.8,
            heatindex_c: 36.7,
            heatindex_f: 98.1,
            dewpoint_c: 19.8,
            dewpoint_f: 67.6,
            will_it_rain: 0,
            chance_of_rain: 4,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.3,
            gust_kph: 6.9,
            uv: 4.4,
            wetbulb_c: 23.9,
            wetbulb_f: 75,
          },
          {
            time_epoch: 1789630200,
            time: "2026-09-17 13:00",
            temp_c: 34.8,
            temp_f: 94.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 277,
            wind_dir: "W",
            pressure_mb: 1005,
            pressure_in: 29.69,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 40,
            cloud: 6,
            feelslike_c: 36.9,
            feelslike_f: 98.4,
            windchill_c: 34.9,
            windchill_f: 94.7,
            heatindex_c: 37.7,
            heatindex_f: 99.9,
            dewpoint_c: 19.3,
            dewpoint_f: 66.7,
            will_it_rain: 0,
            chance_of_rain: 1,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.5,
            gust_kph: 7.2,
            uv: 5.8,
            wetbulb_c: 23.9,
            wetbulb_f: 75,
          },
          {
            time_epoch: 1789633800,
            time: "2026-09-17 14:00",
            temp_c: 35.7,
            temp_f: 96.3,
            is_day: 1,
            condition: {
              text: "Thundery outbreaks in nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/200.png",
              code: 1087,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 289,
            wind_dir: "WNW",
            pressure_mb: 1004,
            pressure_in: 29.65,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 37,
            cloud: 65,
            feelslike_c: 37.9,
            feelslike_f: 100.2,
            windchill_c: 35.7,
            windchill_f: 96.3,
            heatindex_c: 38.4,
            heatindex_f: 101.1,
            dewpoint_c: 18.7,
            dewpoint_f: 65.7,
            will_it_rain: 0,
            chance_of_rain: 5,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 4.5,
            gust_kph: 7.3,
            uv: 4.9,
            wetbulb_c: 23.8,
            wetbulb_f: 74.9,
          },
          {
            time_epoch: 1789637400,
            time: "2026-09-17 15:00",
            temp_c: 35.8,
            temp_f: 96.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 301,
            wind_dir: "WNW",
            pressure_mb: 1003,
            pressure_in: 29.63,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 35,
            cloud: 9,
            feelslike_c: 37.6,
            feelslike_f: 99.7,
            windchill_c: 35.8,
            windchill_f: 96.4,
            heatindex_c: 38,
            heatindex_f: 100.5,
            dewpoint_c: 18.1,
            dewpoint_f: 64.5,
            will_it_rain: 0,
            chance_of_rain: 1,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.6,
            gust_kph: 9.1,
            uv: 2.9,
            wetbulb_c: 23.5,
            wetbulb_f: 74.2,
          },
          {
            time_epoch: 1789641000,
            time: "2026-09-17 16:00",
            temp_c: 35.7,
            temp_f: 96.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 327,
            wind_dir: "NNW",
            pressure_mb: 1003,
            pressure_in: 29.62,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 34,
            cloud: 6,
            feelslike_c: 37,
            feelslike_f: 98.6,
            windchill_c: 35.8,
            windchill_f: 96.4,
            heatindex_c: 37.7,
            heatindex_f: 99.9,
            dewpoint_c: 17.6,
            dewpoint_f: 63.8,
            will_it_rain: 0,
            chance_of_rain: 1,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7,
            gust_kph: 11.2,
            uv: 1.2,
            wetbulb_c: 23.2,
            wetbulb_f: 73.8,
          },
          {
            time_epoch: 1789644600,
            time: "2026-09-17 17:00",
            temp_c: 34.8,
            temp_f: 94.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 8,
            wind_dir: "N",
            pressure_mb: 1002,
            pressure_in: 29.58,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 38,
            cloud: 1,
            feelslike_c: 34.7,
            feelslike_f: 94.5,
            windchill_c: 34.8,
            windchill_f: 94.6,
            heatindex_c: 37,
            heatindex_f: 98.5,
            dewpoint_c: 18.3,
            dewpoint_f: 64.9,
            will_it_rain: 0,
            chance_of_rain: 1,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.6,
            gust_kph: 17,
            uv: 0.2,
            wetbulb_c: 23.3,
            wetbulb_f: 73.9,
          },
          {
            time_epoch: 1789648200,
            time: "2026-09-17 18:00",
            temp_c: 33.2,
            temp_f: 91.8,
            is_day: 1,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 15,
            wind_dir: "NNE",
            pressure_mb: 1004,
            pressure_in: 29.64,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 44,
            cloud: 19,
            feelslike_c: 35,
            feelslike_f: 95,
            windchill_c: 33.2,
            windchill_f: 91.8,
            heatindex_c: 35.7,
            heatindex_f: 96.2,
            dewpoint_c: 19.2,
            dewpoint_f: 66.6,
            will_it_rain: 0,
            chance_of_rain: 2,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9,
            gust_kph: 14.5,
            uv: 0,
            wetbulb_c: 23.4,
            wetbulb_f: 74.1,
          },
          {
            time_epoch: 1789651800,
            time: "2026-09-17 19:00",
            temp_c: 32.3,
            temp_f: 90.1,
            is_day: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 35,
            wind_dir: "NE",
            pressure_mb: 1003,
            pressure_in: 29.61,
            precip_mm: 0.04,
            precip_in: 0,
            snow_cm: 0,
            humidity: 46,
            cloud: 100,
            feelslike_c: 34,
            feelslike_f: 93.2,
            windchill_c: 32.3,
            windchill_f: 90.1,
            heatindex_c: 34.6,
            heatindex_f: 94.3,
            dewpoint_c: 19.3,
            dewpoint_f: 66.7,
            will_it_rain: 0,
            chance_of_rain: 14,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.2,
            gust_kph: 11.6,
            uv: 0,
            wetbulb_c: 23.2,
            wetbulb_f: 73.7,
          },
          {
            time_epoch: 1789655400,
            time: "2026-09-17 20:00",
            temp_c: 31,
            temp_f: 87.7,
            is_day: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 168,
            wind_dir: "SSE",
            pressure_mb: 1005,
            pressure_in: 29.68,
            precip_mm: 0.04,
            precip_in: 0,
            snow_cm: 0,
            humidity: 52,
            cloud: 100,
            feelslike_c: 33,
            feelslike_f: 91.4,
            windchill_c: 31,
            windchill_f: 87.7,
            heatindex_c: 33.4,
            heatindex_f: 92.1,
            dewpoint_c: 19.9,
            dewpoint_f: 67.9,
            will_it_rain: 0,
            chance_of_rain: 15,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.2,
            gust_kph: 11.6,
            uv: 0,
            wetbulb_c: 23.2,
            wetbulb_f: 73.8,
          },
          {
            time_epoch: 1789659000,
            time: "2026-09-17 21:00",
            temp_c: 26.1,
            temp_f: 79,
            is_day: 0,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
              code: 1240,
            },
            wind_mph: 16.3,
            wind_kph: 26.3,
            wind_degree: 215,
            wind_dir: "SW",
            pressure_mb: 1006,
            pressure_in: 29.72,
            precip_mm: 0.53,
            precip_in: 0.02,
            snow_cm: 0,
            humidity: 69,
            cloud: 100,
            feelslike_c: 26.2,
            feelslike_f: 79.2,
            windchill_c: 26.1,
            windchill_f: 79,
            heatindex_c: 27.8,
            heatindex_f: 82.1,
            dewpoint_c: 19.9,
            dewpoint_f: 67.8,
            will_it_rain: 0,
            chance_of_rain: 47,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 26.9,
            gust_kph: 43.2,
            uv: 0,
            wetbulb_c: 21.8,
            wetbulb_f: 71.2,
          },
          {
            time_epoch: 1789662600,
            time: "2026-09-17 22:00",
            temp_c: 25.9,
            temp_f: 78.6,
            is_day: 0,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
              code: 1240,
            },
            wind_mph: 13.4,
            wind_kph: 21.6,
            wind_degree: 204,
            wind_dir: "SSW",
            pressure_mb: 1007,
            pressure_in: 29.73,
            precip_mm: 0.4,
            precip_in: 0.02,
            snow_cm: 0,
            humidity: 71,
            cloud: 100,
            feelslike_c: 26.3,
            feelslike_f: 79.3,
            windchill_c: 25.9,
            windchill_f: 78.6,
            heatindex_c: 27.7,
            heatindex_f: 81.9,
            dewpoint_c: 20.3,
            dewpoint_f: 68.5,
            will_it_rain: 0,
            chance_of_rain: 43,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 24.9,
            gust_kph: 40,
            uv: 0,
            wetbulb_c: 22,
            wetbulb_f: 71.6,
          },
          {
            time_epoch: 1789666200,
            time: "2026-09-17 23:00",
            temp_c: 25.8,
            temp_f: 78.4,
            is_day: 0,
            condition: {
              text: "Smoky haze",
              icon: "//cdn.weatherapi.com/weather/64x64/night/149.png",
              code: 1036,
            },
            wind_mph: 11.6,
            wind_kph: 18.7,
            wind_degree: 219,
            wind_dir: "SW",
            pressure_mb: 1006,
            pressure_in: 29.71,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 70,
            cloud: 100,
            feelslike_c: 26.3,
            feelslike_f: 79.3,
            windchill_c: 25.8,
            windchill_f: 78.4,
            heatindex_c: 27.6,
            heatindex_f: 81.6,
            dewpoint_c: 20,
            dewpoint_f: 68,
            will_it_rain: 0,
            chance_of_rain: 18,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 6.2,
            vis_miles: 3,
            gust_mph: 22.6,
            gust_kph: 36.4,
            uv: 0,
            wetbulb_c: 21.8,
            wetbulb_f: 71.2,
          },
        ],
      },
      {
        date: "2026-09-18",
        date_epoch: 1789689600,
        day: {
          maxtemp_c: 34.1,
          maxtemp_f: 93.4,
          mintemp_c: 25,
          mintemp_f: 77,
          avgtemp_c: 28.7,
          avgtemp_f: 83.6,
          maxwind_mph: 9.8,
          maxwind_kph: 15.8,
          totalprecip_mm: 5.45,
          totalprecip_in: 0.21,
          totalsnow_cm: 0,
          avgvis_km: 9.8,
          avgvis_miles: 6,
          avghumidity: 57,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 66,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Overcast",
            icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
            code: 1009,
          },
          uv: 7,
          avgwetbulb_c: 21.9,
          avgwetbulb_f: 71.5,
          maxwetbulb_c: 22.8,
          maxwetbulb_f: 73.1,
        },
        astro: {
          sunrise: "06:07 AM",
          sunset: "06:22 PM",
          moonrise: "01:13 PM",
          moonset: "11:18 PM",
          moon_phase: "First Quarter",
          moon_illumination: 53,
          is_moon_up: 1,
          is_sun_up: 1,
        },
        hour: [
          {
            time_epoch: 1789669800,
            time: "2026-09-18 00:00",
            temp_c: 25.8,
            temp_f: 78.5,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 228,
            wind_dir: "SW",
            pressure_mb: 1006,
            pressure_in: 29.69,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 67,
            cloud: 100,
            feelslike_c: 26.5,
            feelslike_f: 79.7,
            windchill_c: 25.8,
            windchill_f: 78.5,
            heatindex_c: 27.4,
            heatindex_f: 81.3,
            dewpoint_c: 19.3,
            dewpoint_f: 66.7,
            will_it_rain: 0,
            chance_of_rain: 17,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 20.4,
            gust_kph: 32.8,
            uv: 0,
            wetbulb_c: 21.3,
            wetbulb_f: 70.4,
          },
          {
            time_epoch: 1789673400,
            time: "2026-09-18 01:00",
            temp_c: 25.8,
            temp_f: 78.4,
            is_day: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 253,
            wind_dir: "WSW",
            pressure_mb: 1005,
            pressure_in: 29.69,
            precip_mm: 0.08,
            precip_in: 0,
            snow_cm: 0,
            humidity: 67,
            cloud: 86,
            feelslike_c: 26.6,
            feelslike_f: 79.9,
            windchill_c: 25.8,
            windchill_f: 78.4,
            heatindex_c: 27.3,
            heatindex_f: 81.2,
            dewpoint_c: 19.1,
            dewpoint_f: 66.4,
            will_it_rain: 0,
            chance_of_rain: 20,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 19.7,
            gust_kph: 31.7,
            uv: 0,
            wetbulb_c: 21.2,
            wetbulb_f: 70.2,
          },
          {
            time_epoch: 1789677000,
            time: "2026-09-18 02:00",
            temp_c: 25.3,
            temp_f: 77.6,
            is_day: 0,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
              code: 1240,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 261,
            wind_dir: "W",
            pressure_mb: 1005,
            pressure_in: 29.68,
            precip_mm: 0.5,
            precip_in: 0.02,
            snow_cm: 0,
            humidity: 70,
            cloud: 65,
            feelslike_c: 26.9,
            feelslike_f: 80.4,
            windchill_c: 25.3,
            windchill_f: 77.6,
            heatindex_c: 27,
            heatindex_f: 80.6,
            dewpoint_c: 19.5,
            dewpoint_f: 67.2,
            will_it_rain: 0,
            chance_of_rain: 38,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.9,
            gust_kph: 19.1,
            uv: 0,
            wetbulb_c: 21.3,
            wetbulb_f: 70.4,
          },
          {
            time_epoch: 1789680600,
            time: "2026-09-18 03:00",
            temp_c: 25.7,
            temp_f: 78.3,
            is_day: 0,
            condition: {
              text: "Smoky haze",
              icon: "//cdn.weatherapi.com/weather/64x64/night/149.png",
              code: 1036,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 269,
            wind_dir: "W",
            pressure_mb: 1005,
            pressure_in: 29.68,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 69,
            cloud: 81,
            feelslike_c: 27.5,
            feelslike_f: 81.5,
            windchill_c: 25.7,
            windchill_f: 78.3,
            heatindex_c: 27.4,
            heatindex_f: 81.3,
            dewpoint_c: 19.7,
            dewpoint_f: 67.4,
            will_it_rain: 0,
            chance_of_rain: 14,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 8.2,
            vis_miles: 5,
            gust_mph: 9.4,
            gust_kph: 15.2,
            uv: 0,
            wetbulb_c: 21.5,
            wetbulb_f: 70.8,
          },
          {
            time_epoch: 1789684200,
            time: "2026-09-18 04:00",
            temp_c: 25.8,
            temp_f: 78.5,
            is_day: 0,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
              code: 1240,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 282,
            wind_dir: "WNW",
            pressure_mb: 1005,
            pressure_in: 29.69,
            precip_mm: 0.31,
            precip_in: 0.01,
            snow_cm: 0,
            humidity: 69,
            cloud: 68,
            feelslike_c: 27.6,
            feelslike_f: 81.7,
            windchill_c: 25.8,
            windchill_f: 78.5,
            heatindex_c: 27.5,
            heatindex_f: 81.5,
            dewpoint_c: 19.6,
            dewpoint_f: 67.3,
            will_it_rain: 0,
            chance_of_rain: 36,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.2,
            gust_kph: 14.8,
            uv: 0,
            wetbulb_c: 21.5,
            wetbulb_f: 70.8,
          },
          {
            time_epoch: 1789687800,
            time: "2026-09-18 05:00",
            temp_c: 25.8,
            temp_f: 78.4,
            is_day: 0,
            condition: {
              text: "Smoky haze",
              icon: "//cdn.weatherapi.com/weather/64x64/night/149.png",
              code: 1036,
            },
            wind_mph: 8.1,
            wind_kph: 13,
            wind_degree: 290,
            wind_dir: "WNW",
            pressure_mb: 1006,
            pressure_in: 29.71,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 68,
            cloud: 94,
            feelslike_c: 26.7,
            feelslike_f: 80.1,
            windchill_c: 25.8,
            windchill_f: 78.4,
            heatindex_c: 27.3,
            heatindex_f: 81.2,
            dewpoint_c: 19.3,
            dewpoint_f: 66.7,
            will_it_rain: 0,
            chance_of_rain: 16,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 7.7,
            vis_miles: 4,
            gust_mph: 17.5,
            gust_kph: 28.2,
            uv: 0,
            wetbulb_c: 21.3,
            wetbulb_f: 70.4,
          },
          {
            time_epoch: 1789691400,
            time: "2026-09-18 06:00",
            temp_c: 25.6,
            temp_f: 78.1,
            is_day: 1,
            condition: {
              text: "Smoky haze",
              icon: "//cdn.weatherapi.com/weather/64x64/day/149.png",
              code: 1036,
            },
            wind_mph: 5.6,
            wind_kph: 9,
            wind_degree: 263,
            wind_dir: "W",
            pressure_mb: 1007,
            pressure_in: 29.73,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 66,
            cloud: 100,
            feelslike_c: 27,
            feelslike_f: 80.6,
            windchill_c: 25.6,
            windchill_f: 78.1,
            heatindex_c: 27.1,
            heatindex_f: 80.8,
            dewpoint_c: 18.9,
            dewpoint_f: 66,
            will_it_rain: 0,
            chance_of_rain: 16,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 8,
            vis_miles: 4,
            gust_mph: 11.9,
            gust_kph: 19.1,
            uv: 0,
            wetbulb_c: 21,
            wetbulb_f: 69.8,
          },
          {
            time_epoch: 1789695000,
            time: "2026-09-18 07:00",
            temp_c: 26.4,
            temp_f: 79.6,
            is_day: 1,
            condition: {
              text: "Smoky haze",
              icon: "//cdn.weatherapi.com/weather/64x64/day/149.png",
              code: 1036,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 247,
            wind_dir: "WSW",
            pressure_mb: 1007,
            pressure_in: 29.75,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 63,
            cloud: 70,
            feelslike_c: 27.7,
            feelslike_f: 81.9,
            windchill_c: 26.4,
            windchill_f: 79.6,
            heatindex_c: 27.9,
            heatindex_f: 82.2,
            dewpoint_c: 18.8,
            dewpoint_f: 65.9,
            will_it_rain: 0,
            chance_of_rain: 10,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 8.8,
            vis_miles: 5,
            gust_mph: 8.7,
            gust_kph: 14,
            uv: 0.5,
            wetbulb_c: 21.2,
            wetbulb_f: 70.2,
          },
          {
            time_epoch: 1789698600,
            time: "2026-09-18 08:00",
            temp_c: 27.4,
            temp_f: 81.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 254,
            wind_dir: "WSW",
            pressure_mb: 1008,
            pressure_in: 29.78,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 59,
            cloud: 10,
            feelslike_c: 28.5,
            feelslike_f: 83.3,
            windchill_c: 27.4,
            windchill_f: 81.3,
            heatindex_c: 28.7,
            heatindex_f: 83.7,
            dewpoint_c: 18.6,
            dewpoint_f: 65.4,
            will_it_rain: 0,
            chance_of_rain: 4,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.7,
            gust_kph: 15.6,
            uv: 1.6,
            wetbulb_c: 21.3,
            wetbulb_f: 70.4,
          },
          {
            time_epoch: 1789702200,
            time: "2026-09-18 09:00",
            temp_c: 28.1,
            temp_f: 82.6,
            is_day: 1,
            condition: {
              text: "Partly Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 262,
            wind_dir: "W",
            pressure_mb: 1009,
            pressure_in: 29.81,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 57,
            cloud: 34,
            feelslike_c: 29.3,
            feelslike_f: 84.7,
            windchill_c: 28.1,
            windchill_f: 82.6,
            heatindex_c: 29.6,
            heatindex_f: 85.4,
            dewpoint_c: 18.9,
            dewpoint_f: 66.1,
            will_it_rain: 0,
            chance_of_rain: 5,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.9,
            gust_kph: 15.9,
            uv: 3.4,
            wetbulb_c: 21.8,
            wetbulb_f: 71.2,
          },
          {
            time_epoch: 1789705800,
            time: "2026-09-18 10:00",
            temp_c: 29.4,
            temp_f: 84.9,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 8.1,
            wind_kph: 13,
            wind_degree: 262,
            wind_dir: "W",
            pressure_mb: 1009,
            pressure_in: 29.81,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 52,
            cloud: 100,
            feelslike_c: 30.5,
            feelslike_f: 86.9,
            windchill_c: 29.4,
            windchill_f: 84.9,
            heatindex_c: 30.9,
            heatindex_f: 87.6,
            dewpoint_c: 18.6,
            dewpoint_f: 65.4,
            will_it_rain: 0,
            chance_of_rain: 12,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.2,
            gust_kph: 14.8,
            uv: 5.3,
            wetbulb_c: 22,
            wetbulb_f: 71.5,
          },
          {
            time_epoch: 1789709400,
            time: "2026-09-18 11:00",
            temp_c: 30.9,
            temp_f: 87.5,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 265,
            wind_dir: "W",
            pressure_mb: 1009,
            pressure_in: 29.78,
            precip_mm: 0.24,
            precip_in: 0.01,
            snow_cm: 0,
            humidity: 48,
            cloud: 81,
            feelslike_c: 32,
            feelslike_f: 89.6,
            windchill_c: 30.9,
            windchill_f: 87.5,
            heatindex_c: 32.5,
            heatindex_f: 90.4,
            dewpoint_c: 18.5,
            dewpoint_f: 65.3,
            will_it_rain: 0,
            chance_of_rain: 20,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 8.3,
            gust_kph: 13.3,
            uv: 6.8,
            wetbulb_c: 22.3,
            wetbulb_f: 72.2,
          },
          {
            time_epoch: 1789713000,
            time: "2026-09-18 12:00",
            temp_c: 32.1,
            temp_f: 89.8,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 262,
            wind_dir: "W",
            pressure_mb: 1008,
            pressure_in: 29.76,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 44,
            cloud: 72,
            feelslike_c: 33.2,
            feelslike_f: 91.8,
            windchill_c: 32.1,
            windchill_f: 89.8,
            heatindex_c: 33.8,
            heatindex_f: 92.8,
            dewpoint_c: 18.2,
            dewpoint_f: 64.8,
            will_it_rain: 0,
            chance_of_rain: 6,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.8,
            gust_kph: 12.6,
            uv: 7,
            wetbulb_c: 22.5,
            wetbulb_f: 72.6,
          },
          {
            time_epoch: 1789716600,
            time: "2026-09-18 13:00",
            temp_c: 33.1,
            temp_f: 91.5,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 255,
            wind_dir: "WSW",
            pressure_mb: 1007,
            pressure_in: 29.73,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 41,
            cloud: 96,
            feelslike_c: 34.1,
            feelslike_f: 93.4,
            windchill_c: 33.1,
            windchill_f: 91.5,
            heatindex_c: 34.8,
            heatindex_f: 94.6,
            dewpoint_c: 18,
            dewpoint_f: 64.4,
            will_it_rain: 0,
            chance_of_rain: 9,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7,
            gust_kph: 11.2,
            uv: 6.3,
            wetbulb_c: 22.7,
            wetbulb_f: 72.8,
          },
          {
            time_epoch: 1789720200,
            time: "2026-09-18 14:00",
            temp_c: 33.7,
            temp_f: 92.6,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 246,
            wind_dir: "WSW",
            pressure_mb: 1006,
            pressure_in: 29.7,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 39,
            cloud: 96,
            feelslike_c: 34.3,
            feelslike_f: 93.7,
            windchill_c: 33.7,
            windchill_f: 92.6,
            heatindex_c: 35.4,
            heatindex_f: 95.7,
            dewpoint_c: 17.9,
            dewpoint_f: 64.3,
            will_it_rain: 0,
            chance_of_rain: 9,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.6,
            gust_kph: 12.3,
            uv: 4.7,
            wetbulb_c: 22.8,
            wetbulb_f: 73,
          },
          {
            time_epoch: 1789723800,
            time: "2026-09-18 15:00",
            temp_c: 34.1,
            temp_f: 93.4,
            is_day: 1,
            condition: {
              text: "Partly Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 234,
            wind_dir: "SW",
            pressure_mb: 1005,
            pressure_in: 29.68,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 38,
            cloud: 60,
            feelslike_c: 34.5,
            feelslike_f: 94.1,
            windchill_c: 34.1,
            windchill_f: 93.4,
            heatindex_c: 35.8,
            heatindex_f: 96.5,
            dewpoint_c: 17.8,
            dewpoint_f: 64,
            will_it_rain: 0,
            chance_of_rain: 5,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.4,
            gust_kph: 16.7,
            uv: 2.7,
            wetbulb_c: 22.8,
            wetbulb_f: 73.1,
          },
          {
            time_epoch: 1789727400,
            time: "2026-09-18 16:00",
            temp_c: 33.7,
            temp_f: 92.7,
            is_day: 1,
            condition: {
              text: "Thundery outbreaks in nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/200.png",
              code: 1087,
            },
            wind_mph: 8.1,
            wind_kph: 13,
            wind_degree: 224,
            wind_dir: "SW",
            pressure_mb: 1005,
            pressure_in: 29.67,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 39,
            cloud: 58,
            feelslike_c: 34,
            feelslike_f: 93.2,
            windchill_c: 33.7,
            windchill_f: 92.7,
            heatindex_c: 35.5,
            heatindex_f: 95.8,
            dewpoint_c: 17.9,
            dewpoint_f: 64.2,
            will_it_rain: 0,
            chance_of_rain: 5,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 9.9,
            gust_kph: 15.9,
            uv: 1,
            wetbulb_c: 22.8,
            wetbulb_f: 73,
          },
          {
            time_epoch: 1789731000,
            time: "2026-09-18 17:00",
            temp_c: 32.6,
            temp_f: 90.8,
            is_day: 1,
            condition: {
              text: "Thundery outbreaks in nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/200.png",
              code: 1087,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 207,
            wind_dir: "SSW",
            pressure_mb: 1005,
            pressure_in: 29.68,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 43,
            cloud: 68,
            feelslike_c: 33.9,
            feelslike_f: 93,
            windchill_c: 32.6,
            windchill_f: 90.8,
            heatindex_c: 34.5,
            heatindex_f: 94.1,
            dewpoint_c: 18.4,
            dewpoint_f: 65.2,
            will_it_rain: 0,
            chance_of_rain: 6,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 8.3,
            gust_kph: 13.4,
            uv: 0.2,
            wetbulb_c: 22.8,
            wetbulb_f: 73,
          },
          {
            time_epoch: 1789734600,
            time: "2026-09-18 18:00",
            temp_c: 31,
            temp_f: 87.8,
            is_day: 0,
            condition: {
              text: "Moderate rain at times",
              icon: "//cdn.weatherapi.com/weather/64x64/night/299.png",
              code: 1186,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 192,
            wind_dir: "SSW",
            pressure_mb: 1005,
            pressure_in: 29.68,
            precip_mm: 0.58,
            precip_in: 0.02,
            snow_cm: 0,
            humidity: 48,
            cloud: 86,
            feelslike_c: 32.2,
            feelslike_f: 90,
            windchill_c: 31,
            windchill_f: 87.8,
            heatindex_c: 32.7,
            heatindex_f: 90.9,
            dewpoint_c: 18.6,
            dewpoint_f: 65.5,
            will_it_rain: 0,
            chance_of_rain: 36,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.8,
            gust_kph: 14.2,
            uv: 0,
            wetbulb_c: 22.4,
            wetbulb_f: 72.4,
          },
          {
            time_epoch: 1789738200,
            time: "2026-09-18 19:00",
            temp_c: 29.2,
            temp_f: 84.6,
            is_day: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 8.1,
            wind_kph: 13,
            wind_degree: 170,
            wind_dir: "S",
            pressure_mb: 1006,
            pressure_in: 29.71,
            precip_mm: 2.2,
            precip_in: 0.09,
            snow_cm: 0,
            humidity: 54,
            cloud: 85,
            feelslike_c: 30.5,
            feelslike_f: 86.9,
            windchill_c: 29.2,
            windchill_f: 84.6,
            heatindex_c: 30.8,
            heatindex_f: 87.5,
            dewpoint_c: 18.9,
            dewpoint_f: 66,
            will_it_rain: 0,
            chance_of_rain: 57,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 12.3,
            gust_kph: 19.9,
            uv: 0,
            wetbulb_c: 22.1,
            wetbulb_f: 71.7,
          },
          {
            time_epoch: 1789741800,
            time: "2026-09-18 20:00",
            temp_c: 27.5,
            temp_f: 81.5,
            is_day: 0,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
              code: 1240,
            },
            wind_mph: 8.7,
            wind_kph: 14,
            wind_degree: 296,
            wind_dir: "WNW",
            pressure_mb: 1008,
            pressure_in: 29.78,
            precip_mm: 0.77,
            precip_in: 0.03,
            snow_cm: 0,
            humidity: 62,
            cloud: 74,
            feelslike_c: 29,
            feelslike_f: 84.2,
            windchill_c: 27.5,
            windchill_f: 81.5,
            heatindex_c: 29.3,
            heatindex_f: 84.7,
            dewpoint_c: 19.7,
            dewpoint_f: 67.5,
            will_it_rain: 0,
            chance_of_rain: 42,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.7,
            gust_kph: 18.8,
            uv: 0,
            wetbulb_c: 22.1,
            wetbulb_f: 71.7,
          },
          {
            time_epoch: 1789745400,
            time: "2026-09-18 21:00",
            temp_c: 25,
            temp_f: 77,
            is_day: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 343,
            wind_dir: "NNW",
            pressure_mb: 1010,
            pressure_in: 29.82,
            precip_mm: 0.01,
            precip_in: 0,
            snow_cm: 0,
            humidity: 72,
            cloud: 98,
            feelslike_c: 25.7,
            feelslike_f: 78.3,
            windchill_c: 25,
            windchill_f: 77,
            heatindex_c: 26.7,
            heatindex_f: 80,
            dewpoint_c: 19.6,
            dewpoint_f: 67.2,
            will_it_rain: 0,
            chance_of_rain: 19,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15.2,
            gust_kph: 24.5,
            uv: 0,
            wetbulb_c: 21.2,
            wetbulb_f: 70.2,
          },
          {
            time_epoch: 1789749000,
            time: "2026-09-18 22:00",
            temp_c: 26.9,
            temp_f: 80.4,
            is_day: 0,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
              code: 1240,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 101,
            wind_dir: "ESE",
            pressure_mb: 1008,
            pressure_in: 29.78,
            precip_mm: 0.75,
            precip_in: 0.03,
            snow_cm: 0,
            humidity: 68,
            cloud: 100,
            feelslike_c: 28.6,
            feelslike_f: 83.5,
            windchill_c: 26.9,
            windchill_f: 80.4,
            heatindex_c: 28.9,
            heatindex_f: 84,
            dewpoint_c: 20.5,
            dewpoint_f: 68.9,
            will_it_rain: 0,
            chance_of_rain: 52,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 0,
            wetbulb_c: 22.4,
            wetbulb_f: 72.3,
          },
          {
            time_epoch: 1789752600,
            time: "2026-09-18 23:00",
            temp_c: 26.8,
            temp_f: 80.2,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 162,
            wind_dir: "SSE",
            pressure_mb: 1008,
            pressure_in: 29.77,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 66,
            cloud: 12,
            feelslike_c: 28.3,
            feelslike_f: 82.9,
            windchill_c: 26.8,
            windchill_f: 80.2,
            heatindex_c: 28.5,
            heatindex_f: 83.3,
            dewpoint_c: 19.8,
            dewpoint_f: 67.6,
            will_it_rain: 0,
            chance_of_rain: 5,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.6,
            gust_kph: 9.1,
            uv: 0,
            wetbulb_c: 21.9,
            wetbulb_f: 71.5,
          },
        ],
      },
    ],
  },
  alerts: {
    alert: [],
  },
};
